### ISSUE TITLE
 installing error "libconfig.h" 

### ISSUE THREAD

**Issue by meibinbin** [PacificBiosciences/blasr#154]
Hello

When I run the "make init-submodule" after running "./configure.py --no-pbbam" successfully, it showed such errors:
make update-submodule
make[1]: Entering directory `/home/wubinbin/ToolKits/blasr'
git submodule update --init
make[1]: git: Command not found
make[1]: *** [update-submodule] Error 127
make[1]: Leaving directory `/home/wubinbin/ToolKits/blasr'
make: *** [init-submodule] Error 2

and after when I run the "make all" after, it showed such errors:
iblasr/BlasrHeaders.h:22:23: fatal error: libconfig.h: No such file or directory
compilation terminated.
make: *** [Blasr.o] Error 1

please help me to solve this problem.I am looking forward to your answer as soon as possible.Thanks.

**Comment by pb-cdunn** [comment]
Maybe you have an old version of git? Try `git --version` and `git help submodule`.

**Comment by meibinbin** [comment]
so if I want to install BLASR successfully,I have to install the package 'git' in advance?Do you mean that?

**Comment by mjhsieh** [comment]
You need to use git to download for the submodule in BLASR compilation.

**Comment by pb-cdunn** [comment]
> so if I want to install BLASR successfully,I have to install the package 'git' in advance?

Not quite. You can download a [tarball](http://stackoverflow.com/a/23164066) for **blasr**, and another for **blasr_libcpp**. You will need to run `configure.py` for each separately. If you unpack the latter as `libcpp` within the former, then `make configure-submodule` will still work.

You can also build and install them completely separately. In that case, you will need to be aware that **blasr_libcpp** is actually 3 libraries, and you will have to specify all 3 explicitly when you configure **blasr** to build and link against them.

What we are currently missing is a simple way to build **blasr** against a common installation location, like `/usr/local` and/or `~/local`. Everyone's system is different, so we can only *help* with integration.

**Comment by indapa** [comment]
I am having similar issues, when I compile blasr I get the message:

```
make blasr

Unknown option: -C
usage: git [--version] [--help] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]
g++ -O3 -g -DSHA1_7=\"\" -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/home/indapa/PacBio/blasr_install/blasr/libcpp/alignment -I/home/indapa/PacBio/blasr_install/blasr/libcpp/hdf -I/home/indapa/PacBio/blasr_install/blasr/libcpp/pbdata   -c -o Blasr.o Blasr.cpp
In file included from iblasr/BlasrMiscs.hpp:4:0,
                 from Blasr.cpp:3:
iblasr/BlasrHeaders.h:24:23: fatal error: libconfig.h: No such file or directory
 #include <libconfig.h>
                       ^
compilation terminated.
make: *** [Blasr.o] Error 1

```

I followed the previous steps outlined [here](https://github.com/PacificBiosciences/blasr/blob/master/README.INSTALL.md). 

I'm on CentOS 6.7

**Comment by mhsieh** [comment]
Short answer is to compile a newer version of git, or do
```
sudo yum install https://centos6.iuscommunity.org/ius-release.rpm
sudo yum install git2u-core.x86_64
```
to install newer git.

**Comment by ylipacbio** [comment]
Before we dive too deep into fixing the libconfig.h issues, I am wondering if you can use pitchfork  https://github.com/PacificBiosciences/pitchfork to compile and install blasr. Using pitchfork is current recommended way to compile blasr.

Or you can use blasr binary from analysis tar ball www.pacb.com/support/software-downloads/.

**Comment by indapa** [comment]
I got it! I updated git, and started the install steps again. It worked.

**Comment by indapa** [comment]
OK, the instructions I followed resutls in an executable that doesn't support sam/bam output. I tried to install pitchfork, but installing gcc 4.9 (I tried yum install and building from source failed). Then I tried the binary install from the software downloads, and that failed too. Is my best option the AWS AMI? 

`[INFO]Fri, 02 Dec 2016 16:53:18 - Dec 02, 2016 4:53:17 PM com.pacbio.secondary.common.core.AnalysisContext getConfig
SEVERE: Analysis config file could not be opened
Exception in thread "main" java.io.IOException: Analysis config file could not be opened
	at com.pacbio.secondary.common.core.AnalysisContext.getConfig(AnalysisContext.java:70)
	at com.pacbio.secondary.smrtportal.dbupdate.InitDbData.insertSmrtVersion(InitDbData.java:117)
	at com.pacbio.secondary.smrtportal.dbupdate.InitDbData.<init>(InitDbData.java:57)
	at com.pacbio.secondary.smrtportal.dbupdate.InitDbData.main(InitDbData.java:432)
Caused by: java.io.IOException: Failed to parse xml
	at com.pacbio.secondary.common.core.AnalysisConfig.open(AnalysisConfig.java:50)
	at com.pacbio.secondary.common.core.AnalysisContext.getConfig(AnalysisContext.java:66)
	... 3 more
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 27; An invalid XML character (Unicode: 0x{2}) was found in the value of attribute "{1}" and element is "1b".]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:514)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:215)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:184)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
	at com.pacbio.secondary.common.core.AnalysisConfig.open(AnalysisConfig.java:48)
	... 4 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 27; An invalid XML character (Unicode: 0x{2}) was found in the value of attribute "{1}" and element is "1b".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1375)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.scanAttributeValue(XMLScanner.java:928)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanAttribute(XMLNSDocumentSca
Fatal error: Quitting configuration

Aborting.
nnerImpl.java:436)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:253)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2715)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:607)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:116)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:488)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:835)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1210)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:568)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:211)
	... 8 more
installprompter: Error! Encountered unexpected error at 'line 3530 /home/indapa/smrtanalysis/install/smrtanalysis_2.3.0.140936/admin/bin/installprompter', bailing out...
`

**Comment by mhsieh** [comment]
First of you will need to identify what do you need, if you are using blasr to work with base hdf5 files, you indeed can use the smrtanalysis_2.3.0p5 and we can guide you through that.

If you want to use blasr to work with the pacbio bam files, you should probably post your question in pitchfork issue tracker, and I can help you there (hint: use scientific linux devtoolset-3)

**Comment by indapa** [comment]
@mhsieh - I have reads in fastq format I would like to align against a reference. My input files are not in bam format. I would like to use blasr to produce a bam file of aligned reads to the reference. I wasn't able to get pitchfork installed because I had issues update gcc to v4.9.
