### ISSUE TITLE
--sam is no longer supported in blasr 5.2, but -bam is not a valid option.

### ISSUE THREAD

**Issue by wangyugui** [PacificBiosciences/blasr#258]
Hi.

--sam is no longer supported in blasr 5.2, but --bam is not a valid option.

```
# blasr --version
blasr   5.2.3194382

# blasr /nfs/bio-doc/RNA-seq/rRNA/RNA5S1.fa /usr/bio-ref/GRCh38.p7/GRCh38.dna.fa --sa /usr/bio-ref/GRCh38.p7/GRCh38.dna.fa.s
a --bam --out blasr.bam --printSAMQV --cigarUseSeqMatch --nproc 48 --hitPolicy allbest --bestn 20 --nCandidates 20
ERROR: -bam is not a valid option.

```

**Comment by wangyugui** [comment]
Let's move this to #229

**Comment by wangyugui** [comment]
Hi.

We need to build blasr with pbbam/-DUSE_PBBAM to enable --bam option. but there is a lot of trouble to be fixed. can we restore the --sam support?

1,pbbam need boost 1.55?  so we can't build it on CentOS 7(boost 1.53)

2, some os with boost 1.55+ such as fedora 24 have the last gcc such as 6.x/5.x 
 but the gcc -isystem interface changed in gcc 6.x/5.x, so we need to fix it.

3,when we build blasr with pbbam , but ..
ERROR, could not output alignments in BAM unless input reads are in PacBio BAM or DATASET files.
the fastq input is very common?

**Comment by wangyugui** [comment]
And if --sam is disabled , so --bam should be enabled by default.
but now --bam  is disabled too by default.

**Comment by pb-cdunn** [comment]
> some os with boost 1.55+ such as fedora 24 have the last gcc such as 6.x/5.x
but the gcc -isystem interface changed in gcc 6.x/5.x, so we need to fix it.

Please provide more info on this. Maybe we could fix that quickly.

* https://gcc.gnu.org/onlinedocs/gcc/Preprocessor-Options.html#Preprocessor-Options

I'll let someone else respond to the SAM issues.

**Comment by wangyugui** [comment]
In fedora 24, I have to remove the following in blasr/rules.mk and blasr/libcpp/rules.mk to disable compile error.

```
CPPFLAGS+=$(patsubst %,-isystem%,${SYSINCDIRS})
```

**Comment by pb-cdunn** [comment]
According to the gcc link I posted above:

> This manual documents how to use the GNU compilers, as well as their features and incompatibilities, and how to report bugs. It corresponds to the compilers (GCC) version 7.0.0.

So `-isystem` is still in gcc-7.0.0. Maybe your GNU make is a problem? We really need to see the error message. I could google-chat if you want to screen-share and show me sometime.

`-isystem` is not critical, but I think it might help avoid hashing **boost** headers when we build under **ccache**.

**Comment by wangyugui** [comment]
Yes, -isystem is still exist.

but it cause '#include_next ' error (can't find the file) of system header file .

```
+ cd /root/pacbio/blasr
+ git submodule update --init
+ '[' 0 == 0 ']'
+ rm -rf defines.mk
+ ./configure.py --sub HDF5_INCLUDE=/usr/include HDF5_LIB=/usr/lib64 NOPBBAM=0 PBBAM_INC=/root/pacbio/pbbam/include PBBAM_INC=/root/pacbio/pbbam/include PBBAM_LIB=/root/pacbio/pbbam/lib 'PBBAM_LIBFLAGS=-lpbbam -lhts -lz'
`uname`
Linux
writing to '/root/pacbio/blasr/defines.mk':
"""
LIBPBDATA_LIB        ?= /root/pacbio/blasr/libcpp/pbdata
LIBBLASR_LIBFLAGS    ?= -lblasr
HDF5_LIB             ?= /usr/lib64
DL_LIBFLAGS          ?= -ldl
HDF5_INC             ?= /usr/include
LIBPBDATA_INC        ?= /root/pacbio/blasr/libcpp/pbdata
PBBAM_LIBFLAGS       ?= -lpbbam -lhts -lz
PBBAM_INC            ?= /root/pacbio/pbbam/include
PBBAM_LIB            ?= /root/pacbio/pbbam/lib
PTHREAD_LIBFLAGS     ?= -lpthread
SHELL                ?= bash
RT_LIBFLAGS          ?= -lrt
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
ZLIB_LIBFLAGS        ?= -lz
LIBBLASR_INC         ?= /root/pacbio/blasr/libcpp/alignment
LIBBLASR_LIB         ?= /root/pacbio/blasr/libcpp/alignment
LIBPBIHDF_INC        ?= /root/pacbio/blasr/libcpp/hdf
NOPBBAM              ?= 0
LIBPBIHDF_LIB        ?= /root/pacbio/blasr/libcpp/hdf
LDFLAGS+=-static
"""
----
+ '[' 0 == 0 ']'
+ make clean
rm -f blasr Blasr.o Blasr.d blasr.d
make -C utils clean
make[1]: Entering directory '/root/pacbio/blasr/utils'
make[2]: Entering directory '/root/pacbio/blasr/utils/bam2bax'
make[2]: Leaving directory '/root/pacbio/blasr/utils/bam2bax'
make[2]: Entering directory '/root/pacbio/blasr/utils/bax2bam'
make[2]: Leaving directory '/root/pacbio/blasr/utils/bax2bam'
make[1]: Leaving directory '/root/pacbio/blasr/utils'
make -C extrautils clean
make[1]: Entering directory '/root/pacbio/blasr/extrautils'
make[1]: Leaving directory '/root/pacbio/blasr/extrautils'
+ '[' 0 == 0 ']'
+ make configure-submodule
make -f /root/pacbio/blasr//sub.mk configure-submodule
make[1]: Entering directory '/root/pacbio/blasr'
cd libcpp && ./configure.py
uname -s
uname='Linux'
make[1]: Leaving directory '/root/pacbio/blasr'
+ '[' 0 == 0 ']'
+ make build-submodule
make -C libcpp
make[1]: Entering directory '/root/pacbio/blasr/libcpp'
make libpbdata
make[2]: Entering directory '/root/pacbio/blasr/libcpp'
make -C /root/pacbio/blasr/libcpp//pbdata libconfig.h
make[3]: Entering directory '/root/pacbio/blasr/libcpp/pbdata'
make[3]: 'libconfig.h' is up to date.
make[3]: Leaving directory '/root/pacbio/blasr/libcpp/pbdata'
make -C /root/pacbio/blasr/libcpp//pbdata all
make[3]: Entering directory '/root/pacbio/blasr/libcpp/pbdata'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/pacbio/blasr/libcpp/pbdata'
make[2]: Leaving directory '/root/pacbio/blasr/libcpp'
make libpbihdf
make[2]: Entering directory '/root/pacbio/blasr/libcpp'
make -C /root/pacbio/blasr/libcpp//hdf all
make[3]: Entering directory '/root/pacbio/blasr/libcpp/hdf'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/pacbio/blasr/libcpp/hdf'
make[2]: Leaving directory '/root/pacbio/blasr/libcpp'
make libblasr
make[2]: Entering directory '/root/pacbio/blasr/libcpp'
make -C /root/pacbio/blasr/libcpp//alignment all
make[3]: Entering directory '/root/pacbio/blasr/libcpp/alignment'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/root/pacbio/blasr/libcpp/alignment'
make[2]: Leaving directory '/root/pacbio/blasr/libcpp'
make[1]: Leaving directory '/root/pacbio/blasr/libcpp'
+ '[' 0 == 0 ']'
+ make
g++ -O3 -g -DSHA1_7=\"3194382*\" -std=c++0x -pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD -MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc -fno-builtin-free -fno-omit-frame-pointer  -I/root/pacbio/blasr/libcpp/alignment -I/root/pacbio/blasr/libcpp/hdf -I/root/pacbio/blasr/libcpp/pbdata -isystem/root/pacbio/pbbam/include -isystem/usr/include -DUSE_PBBAM -I/root/pacbio/pbbam/include -I/root/pacbio/htslib  -c -o Blasr.o Blasr.cpp
In file included from /usr/include/c++/6.1.1/ext/string_conversions.h:41:0,
                 from /usr/include/c++/6.1.1/bits/basic_string.h:5402,
                 from /usr/include/c++/6.1.1/string:52,
                 from iblasr/BlasrHeaders.h:6,
                 from iblasr/BlasrMiscs.hpp:4,
                 from Blasr.cpp:3:
/usr/include/c++/6.1.1/cstdlib:75:25: fatal error: stdlib.h: No such file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
<builtin>: recipe for target 'Blasr.o' failed
make: *** [Blasr.o] Error 1
+ '[' 2 == 0 ']'
+ exit 1
[root@FC24 blasr]# rpm -qa |grep ccache
[root@FC24 blasr]#

```

**Comment by pb-cdunn** [comment]
Compiler bug. I think that's fixed here:
* https://gcc.gnu.org/ml/libstdc++/2016-01/msg00025.html

I don't fully understand how `-isystem` causes this, but I guess it must cause some macro to be set. Could you try after changing `-std=c++0x` to `-std=c++11`?

If that doesn't work, then what if you add `#include <stdlib.h>` to the top of `BlasrHeaders.h`? The thing is, we *do* include `stdlib.h` elsewhere in blasr, so that header certainly must be available.

If all else fails, we can remove `-isystem`. I just want to learn as much about the problem as possible while it's repeatable.

**Comment by wangyugui** [comment]
configure without HDF5 will cause the download/rebuild of hdf5.

```
+ cd /root/pacbio/blasr
+ git submodule update --init
+ '[' 0 == 0 ']'
+ rm -rf defines.mk
+ ./configure.py --sub NOPBBAM=0 PBBAM_INC=/root/pacbio/pbbam/include PBBAM_INC=/root/pacbio/pbbam/include PBBAM_LIB=/root/pacbio/pbbam/lib 'PBBAM_LIBFLAGS=-lpbbam -lhts -lz'
`uname`
Linux
writing to '/root/pacbio/blasr/defines.mk':
"""
LIBPBDATA_LIB        ?= /root/pacbio/blasr/libcpp/pbdata
LIBBLASR_LIBFLAGS    ?= -lblasr
SHELL                ?= bash
DL_LIBFLAGS          ?= -ldl
LIBPBDATA_INC        ?= /root/pacbio/blasr/libcpp/pbdata
PBBAM_LIBFLAGS       ?= -lpbbam -lhts -lz
PBBAM_INC            ?= /root/pacbio/pbbam/include
PBBAM_LIB            ?= /root/pacbio/pbbam/lib
PTHREAD_LIBFLAGS     ?= -lpthread
RT_LIBFLAGS          ?= -lrt
HDF5_LIBFLAGS        ?= -lhdf5_cpp -lhdf5
LIBPBDATA_LIBFLAGS   ?= -lpbdata
LIBPBIHDF_LIBFLAGS   ?= -lpbihdf
ZLIB_LIBFLAGS        ?= -lz
LIBBLASR_INC         ?= /root/pacbio/blasr/libcpp/alignment
LIBBLASR_LIB         ?= /root/pacbio/blasr/libcpp/alignment
LIBPBIHDF_INC        ?= /root/pacbio/blasr/libcpp/hdf
NOPBBAM              ?= 0
LIBPBIHDF_LIB        ?= /root/pacbio/blasr/libcpp/hdf
LDFLAGS+=-static
"""
----
+ '[' 0 == 0 ']'
+ make clean
rm -f blasr Blasr.o Blasr.d blasr.d
make -C utils clean
make[1]: Entering directory '/root/pacbio/blasr/utils'
make[2]: Entering directory '/root/pacbio/blasr/utils/bam2bax'
make[2]: Leaving directory '/root/pacbio/blasr/utils/bam2bax'
make[2]: Entering directory '/root/pacbio/blasr/utils/bax2bam'
make[2]: Leaving directory '/root/pacbio/blasr/utils/bax2bam'
make[1]: Leaving directory '/root/pacbio/blasr/utils'
make -C extrautils clean
make[1]: Entering directory '/root/pacbio/blasr/extrautils'
make[1]: Leaving directory '/root/pacbio/blasr/extrautils'
+ '[' 0 == 0 ']'
+ make configure-submodule
make -f /root/pacbio/blasr//sub.mk configure-submodule
make[1]: Entering directory '/root/pacbio/blasr'
cd libcpp && ./configure.py
uname -s
uname='Linux'
cd '/root/pacbio/blasr/libcpp' -> '/root/pacbio/blasr/libcpp/hdf'
curl -k -L https://www.dropbox.com/s/8971bcyy5o42rxb/hdf5-1.8.12-headers.tar.bz2\?dl\=0 | tar xjf -
Traceback (most recent call last):
  File "./configure.py", line 328, in <module>
    main(*sys.argv)
  File "./configure.py", line 322, in main
    configure_nopbbam_skip_hdf(envin)
  File "./configure.py", line 245, in configure_nopbbam_skip_hdf
    HDF_HEADERS = fetch_hdf5_headers()
  File "./configure.py", line 208, in fetch_hdf5_headers
    shell(cmd)
  File "./configure.py", line 27, in shell
    raise Exception('%d <- %r' %(status, cmd))
Exception: 512 <- 'curl -k -L https://www.dropbox.com/s/8971bcyy5o42rxb/hdf5-1.8.12-headers.tar.bz2\\?dl\\=0 | tar xjf -'
/root/pacbio/blasr//sub.mk:9: recipe for target 'configure-submodule' failed
make[1]: *** [configure-submodule] Error 1
make[1]: Leaving directory '/root/pacbio/blasr'
makefile:51: recipe for target 'configure-submodule' failed
make: *** [configure-submodule] Error 2
+ '[' 2 == 0 ']'
+ exit 1
[root@FC24 pacbio]#
```

**Comment by wangyugui** [comment]
the failure of the download of HDF5 is caused by network problem.
there is no need to care about it.

**Comment by wangyugui** [comment]
2016-07-05 2:55 GMT+08:00, Christopher Dunn <notifications@github.com>:
> Compiler bug. I think that's fixed here:
> * https://gcc.gnu.org/ml/libstdc++/2016-01/msg00025.html
>
> I don't fully understand how `-isystem` causes this, but I guess it must
> cause some macro to be set. Could you try after changing `-std=c++0x` to
> `-std=c++11`?
>
> If that doesn't work, then what if you add `#include <stdlib.h>` to the top
> of `BlasrHeaders.h`? The thing is, we *do* include `stdlib.h` elsewhere in
> blasr, so that header certainly must be available.
>
> If all else fails, we can remove `-isystem`. I just want to learn as much
> about the problem as possible while it's repeatable.

```
[root@FC24 blasr]# g++ -O3 -g -DSHA1_7=\"3194382*\" -std=c++0x
-pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD
-MP -fno-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc
-fno-builtin-free -fno-omit-frame-pointer
-I/root/pacbio/blasr/libcpp/alignment -I/root/pacbio/blasr/libcpp/hdf
-I/root/pacbio/blasr/libcpp/pbdata -isystem/root/pacbio/pbbam/include
-isystem/usr/include -DUSE_PBBAM -I/root/pacbio/pbbam/include
-I/root/pacbio/htslib  -c -o Blasr.o Blasr.cpp
In file included from /usr/include/c++/6.1.1/ext/string_conversions.h:41:0,
                 from /usr/include/c++/6.1.1/bits/basic_string.h:5402,
                 from /usr/include/c++/6.1.1/string:52,
                 from iblasr/BlasrHeaders.h:6,
                 from iblasr/BlasrMiscs.hpp:4,
                 from Blasr.cpp:3:
/usr/include/c++/6.1.1/cstdlib:75:25: fatal error: stdlib.h: No such
file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
[root@FC24 blasr]# g++ -O3 -g -DSHA1_7=\"3194382*\" -std=c++11
-pedantic -Wall -Wextra -Wno-div-by-zero -Wno-overloaded-virtual -MMD
-MP -fn
o-builtin-malloc -fno-builtin-calloc -fno-builtin-realloc
-fno-builtin-free -fno-omit-frame-pointer
-I/root/pacbio/blasr/libcpp/alignment -
I/root/pacbio/blasr/libcpp/hdf -I/root/pacbio/blasr/libcpp/pbdata
-isystem/root/pacbio/pbbam/include -isystem/usr/include -DUSE_PBBAM
-I/roo
t/pacbio/pbbam/include -I/root/pacbio/htslib  -c -o Blasr.o Blasr.cpp
In file included from /usr/include/c++/6.1.1/ext/string_conversions.h:41:0,
                 from /usr/include/c++/6.1.1/bits/basic_string.h:5402,
                 from /usr/include/c++/6.1.1/string:52,
                 from iblasr/BlasrHeaders.h:6,
                 from iblasr/BlasrMiscs.hpp:4,
                 from Blasr.cpp:3:
/usr/include/c++/6.1.1/cstdlib:75:25: fatal error: stdlib.h: No such
file or directory
 #include_next <stdlib.h>
                         ^
compilation terminated.
[root@FC24 blasr]#
```

**Comment by pb-cdunn** [comment]
(Markdown doesn't work when you respond via email.)

That's what I figured. So you'll need to re-run `configure.py` with `HDF5_INC=.`, or without `HDF5_INC` at all (if that works). That way, you will not have `/usr/include` explicitly in your include path.

**Comment by mhsieh** [comment]
I would like to point out we have not tested anything on gcc 6 yet.

**Comment by pb-cdunn** [comment]
MJ, @wangyugui is performing a great service for us. Also, I highly recommend following the link I posted. It explains the whole thing. We might need to update pitchfork somehow, since `/usr/include` can definitely be configured there. Could you open a pitchfork Issue where we can discuss it further?

@wangyugui, please re-run configure and try again. Hopefully that will solve it.

**Comment by mhsieh** [comment]
By the way we also need boost to be newer than 1.58 for pbbam. by the way we can discuss the issue at https://github.com/PacificBiosciences/pitchfork/issues/265
