### ISSUE TITLE
pbalign

### ISSUE THREAD

**Issue by aquillah** [PacificBiosciences/blasr#382]
I am trying to use pbalign to map read to a reference assembly bu i keep getting this error;
ERROR: -out is not a valid option.
[]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pbcommand/cli/core.py", line 137, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pbalign-0.3.0-py2.7.egg/pbalign/pbalignrunner.py", line 283, in args_runner
    return PBAlignRunner(args, output_dataset_type=output_dataset_type).start()
  File "/usr/local/lib/python2.7/dist-packages/pbcore-1.2.10-py2.7.egg/pbcore/util/ToolRunner.py", line 112, in start
    return self.run()
  File "/usr/local/lib/python2.7/dist-packages/pbalign-0.3.0-py2.7.egg/pbalign/pbalignrunner.py", line 239, in run
    self._alnService.run()
  File "/usr/local/lib/python2.7/dist-packages/pbalign-0.3.0-py2.7.egg/pbalign/alignservice/align.py", line 198, in run
    raise RuntimeError(str(e))
RuntimeError: BlasrService returned a non-zero exit status 1: 

The command i used was; 
$ pbalign reads.fasta assembly.fasta mapped-assembly.bam

**Comment by phpeters** [comment]
The reason is that pbalign calls blasr with flags like "--out" or "--sam". 
A hack-ish solution:
change the flags in function "def _toCmd" in the file
/your/python2.7/path/lib/python2.7/site-packages/pbalign/alignservice/blasr.py
from e.g. "--out" to "-out"
