### ISSUE TITLE
AttributeError: 'int' object has no attribute 'replace'

### ISSUE THREAD

**Issue by kiran0991** [PacificBiosciences/blasr#49]
I am working on insect sized genome de novo assembly using Short Read and Long Reads. 

Assembly step is completed with N50 = 12335, Max = 147590 and Min = 500. Genome size 220 Mb. 

While runing PBjelly with Long Reads able successfully complete setup, mapping and support. However whitel running extraction step, getting an Attribure error as below.  Attempted with different datasets but same error again. 
Referece Input = Velvet.fasta
Reads : LongReads.fastq

[WARNING] Couldn't find CA.qual... assuming there isn't a quality file for the reference
2015-02-12 15:51:03,988 [INFO] Running /data/Program/PBSuite_14.9.9/bin/Extraction.py Protocol.xml
[WARNING] Couldn't find CA.qual... assuming there isn't a quality file for the reference
2015-02-12 15:51:05,235 [INFO] Opening GML Files
2015-02-12 15:51:05,236 [WARNING] It is unknown if networkx version 1.6 will work.
2015-02-12 15:51:05,236 [WARNING] If you get an error here, please report it!!!
2015-02-12 15:51:30,707 [INFO] Loading Reference Sequence
2015-02-12 15:51:37,253 [INFO] Extracting Reads
2015-02-12 15:51:37,253 [INFO] Parsing Velvet.fasta
2015-02-12 15:51:47,207 [INFO] Selective loading from 191309 reads
2015-02-12 15:52:29,079 [INFO] Loaded 23535 Reads
2015-02-12 15:52:34,208 [INFO] Flushing Output Queue of 20000 gaps 20088 reads
Traceback (most recent call last):
  File "/data/Program/PBSuite_14.9.9/bin//Extraction.py", line 337, in <module>
    me.run()
  File "/data/Program/PBSuite_14.9.9/bin//Extraction.py", line 310, in run
    self.__extractReads__()
  File "/data/Program/PBSuite_14.9.9/bin//Extraction.py", line 210, in __extractReads__
    self.flushQueue(outputQueue)
  File "/data/Program/PBSuite_14.9.9/bin//Extraction.py", line 233, in flushQueue
    outFile = self.openGapOut(gapName)
  File "/data/Program/PBSuite_14.9.9/bin//Extraction.py", line 246, in openGapOut
    basedir = os.path.join(self.supportFolder, gapName.replace('/','.'))
AttributeError: 'int' object has no attribute 'replace'

Looking forward to know about the issue.

**Comment by mchaisso** [comment]
Perhaps you should bring up this issue with Adam English the author of PBJelly?  This does not appear to be a blasr issue.
