### ISSUE TITLE
'set_defs_submodule_defaults' is not defined

### ISSUE THREAD

**Issue by cancan101** [PacificBiosciences/blasr#75]
```
Traceback (most recent call last):
  File "./configure.py", line 194, in <module>
    main(*sys.argv)
  File "./configure.py", line 187, in main
    set_defs_submodule_defaults(envin, conf.no_pbbam)
NameError: global name 'set_defs_submodule_defaults' is not defined
```

**Comment by pb-cdunn** [comment]
If you're using `--no-pbbam`, you'll still have this problem:
```
 included from MappingIPC.h:14:0,
                 from Blasr.cpp:15:
./libcpp/alignment/files/ReaderAgglomerate.hpp:16:28: fatal error: HDFBasReader.hpp: No such file or directory
```
If so, re-open. Hopefully we'll have that solved soon.
